In [2]:
import csv
import pandas as pd
import numpy as np

In [3]:
file = 'C:/Users/anna/Desktop/maria/Upwork/ML courses/Sample_Data.xlsx'
data = pd.read_excel(file, encoding="utf8")

In [4]:
print(data.dtypes)

ID number       int64
Outcome        object
Time            int64
Feature 1     float64
Feature 2     float64
Feature 3     float64
Feature 4     float64
Feature 5     float64
Feature 6     float64
Feature 7     float64
Feature 8     float64
Feature 9     float64
Feature 10    float64
Feature 11    float64
Feature 12    float64
Feature 13    float64
Feature 14    float64
Feature 15    float64
Feature 16    float64
Feature 17    float64
Feature 18    float64
Feature 19    float64
Feature 20    float64
Feature 21    float64
Feature 22    float64
Feature 23    float64
Feature 24    float64
Feature 25    float64
Feature 26    float64
Feature 27    float64
Feature 28    float64
Feature 29    float64
Feature 30    float64
Feature 31    float64
Feature 32     object
dtype: object


In [5]:
# Drop missing rows
data.dropna()

ID number Outcome  Time  Feature 1  Feature 2  Feature 3  Feature 4  \
0       119513       N    31      18.02      27.60     117.50     1013.0   
1         8423       N    61      17.99      10.38     122.80     1001.0   
2       842517       N   116      21.37      17.44     137.50     1373.0   
3       843483       N   123      11.42      20.38      77.58      386.1   
4       843584       R    27      20.29      14.34     135.10     1297.0   
5       843786       R    77      12.75      15.29      84.60      502.7   
6       844359       N    60      18.98      19.61     124.40     1112.0   
7       844582       R    77      13.71      20.83      90.20      577.9   
8       844981       N   119      13.00      21.82      87.50      519.8   
9       845010       N    76      12.46      24.04      83.97      475.9   
10      845636       N   123      16.02      23.24     102.70      797.8   
11      846100       N   125      15.78      17.89     103.60      781.0   
12      846381       N   117      15.85      23.95     103.70      782.7   
13      847990       R    36      14.54      27.54      96.73      658.8   
14      848406       N   123      14.68      20.13      94.74      684.5   
15      848620       R    10      16.13      20.68     108.10      798.8   
16     8511133       N    20      15.34      14.26     102.50      704.4   
17      851509       R    10      21.16      23.04     137.20     1404.0   
18      852552       N    96      16.65      21.38     110.00      904.6   
19      852631       N   116      17.14      16.40     116.00      912.7   
20      852763       N   103      14.58      21.53      97.41      644.8   
21      852781       N    16      18.61      20.25     122.10     1094.0   
22      852973       N    52      15.30      25.27     102.40      732.4   
23      853201       N    94      17.57      15.05     115.00      955.1   
24      853612       N   116      11.84      18.70      77.93      440.6   
25      853826       N    87      17.02      23.98     112.80      899.3   
26      854002       N    53      19.27      26.47     127.90     1162.0   
27      854039       N   109      16.13      17.88     107.00      807.2   
28      854253       N    12      16.74      21.59     110.10      869.5   
29      854268       N    31      14.25      21.72      93.63      633.0   
..         ...     ...   ...        ...        ...        ...        ...   
168     925622       N    30      15.22      30.62     103.40      716.9   
169     926125       N    17      20.92      25.09     143.00     1347.0   
170     926424       N    28      21.56      22.39     142.00     1479.0   
171     926682       N    20      20.13      28.25     131.20     1261.0   
172     926954       N    16      16.60      28.08     108.30      858.1   
173     927992       N    26      13.86      23.83      89.60      595.8   
174     927997       N    27      18.11      26.17     118.70      970.2   
175     928594       N    29      21.93      30.64     146.70     1487.0   
176     929684       R    14      17.53      25.28     114.00      966.6   
177     931652       R     1      18.11      30.99     115.80      984.4   
178     931678       N    24      24.29      25.48     161.80     1715.0   
179     935058       N    13      15.60      26.79      99.85      760.0   
180     935878       N    13      15.78      17.10     102.20      769.0   
181     937100       N    12      19.28      20.88     124.90     1127.0   
182     937653       N    15      15.66      24.51     102.00      771.1   
183     937654       N    11      22.44      27.42     150.60     1504.0   
184     937664       N    17      17.98      23.96     120.00      995.0   
185     937897       N    17      13.63      24.70      89.65      569.2   
186     938225       N     9      23.01      33.87     156.80     1705.0   
187     938412       N    10      22.41      29.95     145.50     1528.0   
188     938413       N    15      12.53      30.98   

In [6]:
# Find the indices of the rows where the outcome is N (= nonrecur)
indexNames = data[data['Outcome'] == 'N'].index

In [7]:
# Delete these row indexes from dataFrame
data.drop(indexNames , inplace=True)

In [8]:
# It is easier to have adjacent indices
data = data.reset_index()

In [9]:
print(data)

    index  ID number Outcome  Time  Feature 1  Feature 2  Feature 3  \
0       4     843584       R    27      20.29      14.34     135.10   
1       5     843786       R    77      12.75      15.29      84.60   
2       7     844582       R    77      13.71      20.83      90.20   
3      13     847990       R    36      14.54      27.54      96.73   
4      15     848620       R    10      16.13      20.68     108.10   
5      17     851509       R    10      21.16      23.04     137.20   
6      34     855625       R     9      19.07      24.81     128.30   
7      37     857010       R     8      18.65      17.60     123.70   
8      39     857438       R    48      15.10      22.02      97.26   
9      40     857637       R    11      19.21      18.57     125.50   
10     42     858986       R    34      14.25      22.15      96.42   
11     43     859223       R    19      12.68      23.84      82.69   
12     46     859983       R    26      13.80      15.79      90.43   
13    

In [10]:
temp = data.iloc[:,3:36]
print(temp)

    Time  Feature 1  Feature 2  Feature 3  Feature 4  Feature 5  Feature 6  \
0     27      20.29      14.34     135.10     1297.0    0.10030    0.13280   
1     77      12.75      15.29      84.60      502.7    0.11890    0.15690   
2     77      13.71      20.83      90.20      577.9    0.11890    0.16450   
3     36      14.54      27.54      96.73      658.8    0.11390    0.15950   
4     10      16.13      20.68     108.10      798.8    0.11700    0.20220   
5     10      21.16      23.04     137.20     1404.0    0.09428    0.10220   
6      9      19.07      24.81     128.30     1104.0    0.09081    0.21900   
7      8      18.65      17.60     123.70     1076.0    0.10990    0.16860   
8     48      15.10      22.02      97.26      712.8    0.09056    0.07081   
9     11      19.21      18.57     125.50     1152.0    0.10530    0.12670   
10    34      14.25      22.15      96.42      645.7    0.10490    0.20080   
11    19      12.68      23.84      82.69      499.0    0.11220 

In [11]:
#temp.apply(lambda s: pd.to_numeric(s, errors='coerce').notnull().all())
# Check if all rows are real numbers. Initially, it checks per element (applymap) and it returns True only if the whole row
# is True (all(1))
b = temp.applymap(np.isreal).all(1)
b.columns = ['truth']
print(b)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43     True
44     True
45     True
46    False
dtype: bool


In [12]:
idx = []     # this list will contain the row indices that are False
for i in range(len(b)): 
    # check if rows are True and if False, append the index in the list
    if not b.iloc[i]:
        idx.append(i)

In [13]:
# Delete these row indexes from the initial dataFrame (data)
data.drop(data.index[idx], inplace=True)

In [14]:
#print(data.dtypes)
feat = data.iloc[:,4:36]
lab = data.iloc[:,3]

In [114]:
# Transform them to np arrays
print(lab.dtype)
print(type(lab))

int64
<class 'pandas.core.series.Series'>


In [233]:
%matplotlib inline
import d2l
from mxnet import autograd, np, npx, nd
import mxnet as mx
import random
npx.set_np()

In [234]:
l = np.array(lab)
labels = l.astype('float32') 
print(labels)
#print(l.dtype)
#print(type(l))

[27. 77. 77. 36. 10. 10.  9.  8. 48. 11. 34. 19. 26. 40. 10. 35. 73.  7.
 44.  8. 17. 74. 17. 19. 39. 12. 37.  5. 58. 78. 24. 33.  4.  5.  2. 49.
  1.  9. 16.  9. 14. 12. 11.  7. 14.  1.]


In [235]:
f = np.array(feat)
features = f.astype('float32') 
print(features)
#print(f.dtype)
#print(type(f))

[[2.029e+01 1.434e+01 1.351e+02 ... 7.678e-02 3.500e+00 0.000e+00]
 [1.275e+01 1.529e+01 8.460e+01 ... 1.179e-01 2.500e+00 0.000e+00]
 [1.371e+01 2.083e+01 9.020e+01 ... 1.151e-01 4.000e+00 1.000e+01]
 ...
 [2.424e+01 1.874e+01 1.596e+02 ... 6.259e-02 3.000e+00 4.000e+00]
 [1.753e+01 2.528e+01 1.140e+02 ... 7.156e-02 1.000e+01 9.000e+00]
 [1.811e+01 3.099e+01 1.158e+02 ... 7.006e-02 2.700e+00 4.000e+00]]


In [250]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # The examples are read at random, in no particular order
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = np.array(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [457]:
batch_size = 10

for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

[[1.275e+01 1.529e+01 8.460e+01 5.027e+02 1.189e-01 1.569e-01 1.664e-01
  7.666e-02 1.995e-01 7.164e-02 3.877e-01 7.402e-01 2.999e+00 3.085e+01
  7.775e-03 2.987e-02 4.561e-02 1.357e-02 1.774e-02 5.114e-03 1.551e+01
  2.037e+01 1.073e+02 7.332e+02 1.706e-01 4.196e-01 5.999e-01 1.709e-01
  3.485e-01 1.179e-01 2.500e+00 0.000e+00]
 [1.729e+01 2.213e+01 1.144e+02 9.478e+02 8.999e-02 1.273e-01 9.697e-02
  7.507e-02 2.108e-01 5.464e-02 8.348e-01 1.633e+00 6.146e+00 9.094e+01
  6.717e-03 5.981e-02 4.638e-02 2.149e-02 2.747e-02 5.838e-03 2.039e+01
  2.724e+01 1.379e+02 1.295e+03 1.134e-01 2.867e-01 2.298e-01 1.528e-01
  3.067e-01 7.484e-02 4.000e+00 1.000e+00]
 [2.424e+01 1.874e+01 1.596e+02 1.945e+03 8.938e-02 1.136e-01 1.727e-01
  1.071e-01 1.591e-01 5.175e-02 1.730e+00 8.535e-01 1.156e+01 3.160e+02
  5.137e-03 1.279e-02 2.353e-02 1.508e-02 1.615e-02 2.252e-03 3.513e+01
  2.336e+01 2.322e+02 3.903e+03 1.154e-01 1.772e-01 2.917e-01 1.795e-01
  2.336e-01 6.259e-02 3.000e+00 4.000e+00]
 [1.775

In [458]:
w = np.random.normal(0, 1e-10, (32,1))
b = np.zeros(1)

In [459]:
w.attach_grad()
b.attach_grad()

In [460]:
# Saved in the d2l package for later use
def linreg(X, w, b):
    regr = np.dot(X, w) + b
    #print('X', X)
    #print('Regr', regr)
    return regr

In [461]:
print(w.shape, b.shape)
print(features.shape, labels.shape)
# f* w + b = l

(32, 1) (1,)
(46, 32) (46,)


In [462]:
# Saved in the d2l package for later use
def squared_loss(y_hat, y):
    #print('regr output', y_hat)
    #print('yhat - y:',(y_hat - y.reshape(y_hat.shape))** 2 / 2  )
    sq_loss = (y_hat - y.reshape(y_hat.shape)) ** 2 / 2
    return sq_loss

In [463]:
# Saved in the d2l package for later use
def sgd(params, lr, batch_size):
    for param in params:
        param[:] = param - lr * param.grad / batch_size

In [464]:
# In our case, big learning rate gets the gradient large very fast, so the output of the linear regression becomes infinite
# therefore the loss function becomes infinite as well
# until 1e-7 everything is ok, but if you go down to 1e-6, the gradient starts exploding again!
lr = 1e-7  # Learning rate

# Smaller learning rate means we learn slowly, so we can increase the number of epochs, until the point 
# the loss starts increasing again
num_epochs = 100  # Number of iterations

net = linreg  # Our fancy linear model
loss = squared_loss  # 0.5 (y-y')^2

In [465]:
for epoch in range(num_epochs):
    # Assuming the number of examples can be divided by the batch size, all
    # the examples in the training dataset are used once in one epoch
    # iteration. The features and tags of minibatch examples are given by X
    # and y respectively
    for X, y in data_iter(batch_size, features, labels):
        with autograd.record():
            l = loss(net(X, w, b), y)  # Minibatch loss in X and y
        l.backward()  # Compute gradient on l with respect to [w, b]
        sgd([w, b], lr, batch_size)  # Update parameters using their gradient
    train_l = loss(net(features, w, b), labels)
    print('epoch %d, loss %f' % (epoch + 1, train_l.mean().asnumpy()))

epoch 1, loss 374.042084
epoch 2, loss 383.830078
epoch 3, loss 372.009308
epoch 4, loss 371.146698
epoch 5, loss 371.072815
epoch 6, loss 371.000397
epoch 7, loss 370.216492
epoch 8, loss 380.395111
epoch 9, loss 371.651947
epoch 10, loss 371.086060
epoch 11, loss 371.625397
epoch 12, loss 369.494385
epoch 13, loss 367.876007
epoch 14, loss 383.181305
epoch 15, loss 366.800781
epoch 16, loss 367.044891
epoch 17, loss 365.556732
epoch 18, loss 365.431000
epoch 19, loss 365.190857
epoch 20, loss 365.546844
epoch 21, loss 364.269287
epoch 22, loss 366.632294
epoch 23, loss 363.222626
epoch 24, loss 363.971344
epoch 25, loss 365.917114
epoch 26, loss 365.077789
epoch 27, loss 362.811951
epoch 28, loss 363.856964
epoch 29, loss 371.256927
epoch 30, loss 361.549347
epoch 31, loss 361.392059
epoch 32, loss 366.647125
epoch 33, loss 361.018158
epoch 34, loss 362.172211
epoch 35, loss 358.915588
epoch 36, loss 363.737946
epoch 37, loss 363.813507
epoch 38, loss 358.870667
epoch 39, loss 360.64